#!/bin/bash
set -e
script_dir=$(cd $(dirname $0);pwd)
ROOT=$(dirname $script_dir)
ROOT_TMP=$ROOT.tmp
project_name=$(basename $ROOT)
flutter_version=$(flutter --version |head -1|awk '{print $2}')
echo update $ROOT
mv $ROOT $ROOT_TMP
$ROOT_TMP/script/create $ROOT
cd $ROOT_TMP
for i in .git .github LICENSE script README.md */README.md
do
  mv $ROOT_TMP/$i $ROOT/$(dirname $i)
done
cd $ROOT
sed -i 's/Sample Items/Sample Items AoEiuV020/' lib/src/sample_feature/sample_item_list_view.dart
sed -i "s/^version: 1\.0\.0[+]1/version: ${flutter_version}+1/" pubspec.yaml
git status
rm -rf $ROOT_TMP
