#!/bin/bash
set -e
script_dir=$(cd $(dirname $0);pwd)
ROOT=$(dirname $script_dir)
ROOT_TMP=$ROOT.tmp
project_name=$(basename $ROOT)
flutter_version=$(flutter --version |head -1|awk '{print $2}')
echo update $ROOT
mv $ROOT $ROOT_TMP
$ROOT_TMP/script/create $ROOT
cd $ROOT_TMP
for i in .git .github LICENSE script README.md */README.md android/gradle/signing.gradle
do
  mv $ROOT_TMP/$i $ROOT/$(dirname $i)
done
cd $ROOT
# 改主页标题，
sed -i 's/\(Flutter Demo\)/\1 AoEiuV020/' lib/main.dart
# 改app版本号为flutter自身的版本号，
sed -i "s/^version: 1\.0\.0[+]1/version: ${flutter_version}+1/" pubspec.yaml
# 安卓签名配置，
cat <<EOF >> android/app/build.gradle
apply(rootProject.file("gradle/signing.gradle"))
EOF

git status
rm -rf $ROOT_TMP
